runtime: node.js
env: flex

# update with Redis instance network name
network:
    name: default

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

- url: /*
  secure: always
  script: auto



automatic_scaling:
  min_num_instances: 0
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.5