runtime: node.js
env: flex

# update with Redis instance network name
network:
    name: default

automatic_scaling:
  cool_down_period: 120s
  min_num_instances: 0
  max_num_instances: 10
  cpu_utilization:
    target_utilization: 0.5