runtime: nodejs10
env: standard

instance_class: F2

# update with Redis instance network name
#network:
#    name: default

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_throughput_utilization: 0.6