const countryOptions = [
    { key: 'af', value: 'AF', flag: 'af', text: 'Afghanistan' },
    { key: 'ax', value: 'AX', flag: 'ax', text: 'Aland Islands' },
    { key: 'al', value: 'AL', flag: 'al', text: 'Albania' },
    { key: 'dz', value: 'DZ', flag: 'dz', text: 'Algeria' },
    { key: 'as', value: 'AS', flag: 'as', text: 'American Samoa' },
    { key: 'ad', value: 'AD', flag: 'ad', text: 'Andorra' },
    { key: 'ao', value: 'AO', flag: 'ao', text: 'Angola' },
    { key: 'ai', value: 'AI', flag: 'ai', text: 'Anguilla' },
    { key: 'ag', value: 'AG', flag: 'ag', text: 'Antigua' },
    { key: 'ar', value: 'AR', flag: 'ar', text: 'Argentina' },
    { key: 'am', value: 'AM', flag: 'am', text: 'Armenia' },
    { key: 'aw', value: 'AW', flag: 'aw', text: 'Aruba' },
    { key: 'au', value: 'AU', flag: 'au', text: 'Australia' },
    { key: 'at', value: 'AT', flag: 'at', text: 'Austria' },
    { key: 'az', value: 'AZ', flag: 'az', text: 'Azerbaijan' },
    { key: 'bs', value: 'BS', flag: 'bs', text: 'Bahamas' },
    { key: 'bh', value: 'BH', flag: 'bh', text: 'Bahrain' },
    { key: 'bd', value: 'BD', flag: 'bd', text: 'Bangladesh' },
    { key: 'bb', value: 'BB', flag: 'bb', text: 'Barbados' },
    { key: 'by', value: 'BY', flag: 'by', text: 'Belarus' },
    { key: 'be', value: 'BE', flag: 'be', text: 'Belgium' },
    { key: 'bz', value: 'BZ', flag: 'bz', text: 'Belize' },
    { key: 'bj', value: 'BJ', flag: 'bj', text: 'Benin' },
    { key: 'fr', value: 'FR', flag: 'fr', text: 'France' },
    { key: 'de', value: 'DE', flag: 'de', text: 'Germany' },
    { key: 'gb', value: 'GB', flag: 'gb', text: 'Great Britain' },
    { key: 'us', value: 'US', flag: 'us', text: 'United States' },
    { key: 've', value: 'VE', flag: 've', text: 'Venezuela' },
  ];

export default countryOptions;